title: "Question"
description: "Ask a question about SymbolicDSGE"
labels:
  - question
  - from-website
body:
  - type: textarea
    id: question
    attributes:
      label: Your question
      description: Provide as much detail as possible
      placeholder: Describe your question here
    validations:
      required: true
